version: '3'

services:

  db:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - .data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  router:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./router
    ports:
      - 3050:80

  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_USER=$DB_USER
      - MYSQL_PASS=$DB_PASS
      - MYSQL_NAME=$DB_NAME
      - MYSQL_PORT=$DB_PORT
    stdin_open: true
    tty: true
  
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app