version: "3"

services:
  db:
    image: "mysql:8"
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - .data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  router:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./router
    ports:
      - 3050:80

  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./api
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_USER=$DB_USER
      - MYSQL_PASS=$DB_PASS
      - MYSQL_NAME=$DB_NAME
      - MYSQL_PORT=$DB_PORT
      - ROOT_USER=$ROOT_USERNAME
      - ROOT_PASS=$ROOT_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - DEBUG=false

  client:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
